/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (NXP) version 5.38                     *
*        Compiled Nov 24 2016, 16:56:53                              *
*                                                                    *
*        (c) 1998 - 2016 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontSong.c                                            *
* Font:        宋体                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Read pattern file: C:\Users\Administrator\Desktop\新建文本文档.txt *
* Read pattern file: C:\Users\Administrator\Desktop\新建文本文档.txt *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\新建文本文档.txt *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_002E[ 16] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _____X__,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X____X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _____X__,
  ___XX___,
  _____X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ___X_X__,
  __X__X__,
  __X__X__,
  _X___X__,
  _X___X__,
  _XXXXXX_,
  _____X__,
  _____X__,
  ___XXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ___XXX__,
  __X__X__,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___X__,
  _X___X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__XX_,
  ___XX_X_,
  ______X_,
  ______X_,
  __X__X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0041[ 16] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0042[ 16] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0043[ 16] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0044[ 16] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0045[ 16] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X____X_,
  _X____X_,
  XXXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_004C[ 16] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_004F[ 16] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0053[ 16] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  _X______,
  __X_____,
  ___XX___,
  _____X__,
  ______X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0055[ 16] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  ___XXXX_,
  __X___X_,
  _X____X_,
  _X____X_,
  __XXXXXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0063[ 16] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XXX__,
  __X___X_,
  _X______,
  _X______,
  _X______,
  __X___X_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0065[ 16] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _XXXXXX_,
  _X______,
  _X______,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_006B[ 16] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X__XXX_,
  _X__X___,
  _X_X____,
  _XX_X___,
  _X__X___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0070[ 16] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  _XXXX___,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_0073[ 16] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X______,
  __XXXX__,
  ______X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_4F11[ 32] = { /* code 4F11 */
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,_X______,
  ___X_XXX,XXXXXXX_,
  __XX____,_X______,
  __XX____,XXX_____,
  _X_X____,XXX_____,
  X__X___X,_X_X____,
  ___X___X,_X_X____,
  ___X__X_,_X__X___,
  ___X_X__,_X___X__,
  ___XX___,_X____X_,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_4F59[ 32] = { /* code 4F59 */
  _______X,________,
  _______X,________,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,___X____,
  __X_XXXX,XXX_X___,
  XX_____X,_____XX_,
  _______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  ___X___X,___X____,
  ___X___X,____X___,
  __X____X,_____X__,
  _X___X_X,_____X__,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_4F5C[ 32] = { /* code 4F5C */
  ____X__X,________,
  ____X__X,________,
  ____X__X,________,
  ___X___X,XXXXXXX_,
  ___X__X_,X_______,
  __XX__X_,X_______,
  __XX_X__,X_______,
  _X_X____,XXXXX___,
  X__X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,XXXXXX__,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_503C[ 32] = { /* code 503C */
  ____X___,_X______,
  ____X___,_X______,
  ____XXXX,XXXXXX__,
  ___X____,_X______,
  ___X____,_X______,
  __XX__XX,XXXXX___,
  __XX__X_,____X___,
  _X_X__XX,XXXXX___,
  X__X__X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  ___X__X_,____X___,
  ___XXXXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5145[ 32] = { /* code 5145 */
  ______X_,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,________,
  _____X__,________,
  ____X___,__X_____,
  ___X____,___X____,
  __XXXXXX,XXXXX___,
  _____X__,_X__X___,
  _____X__,_X______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,_X___X__,
  ____X___,_X___X__,
  ___X____,_X___X__,
  _XX_____,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_516D[ 32] = { /* code 516D */
  ______X_,________,
  _______X,________,
  ________,X_______,
  ________,X_______,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  _____X__,_X______,
  _____X__,__X_____,
  ____X___,___X____,
  ____X___,____X___,
  ___X____,____X___,
  __X_____,_____X__,
  _X______,_____X__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5185[ 32] = { /* code 5185 */
  _______X,________,
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _X____X_,X____X__,
  _X____X_,_X___X__,
  _X___X__,__X__X__,
  _X__X___,___X_X__,
  _X_X____,___X_X__,
  _X______,_____X__,
  _X______,_____X__,
  _X______,___X_X__,
  _X______,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5199[ 32] = { /* code 5199 */
  ________,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X__X____,_____X__,
  ___X____,________,
  ___XXXXX,XXXXX___,
  ___X____,________,
  __X_____,________,
  __XXXXXX,XXXXX___,
  ________,____X___,
  ________,____X___,
  XXXXXXXX,XX__X___,
  ________,____X___,
  ________,____X___,
  ________,_X_X____,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_521D[ 32] = { /* code 521D */
  __X_____,________,
  ___X____,________,
  _______X,XXXXXX__,
  XXXXXX__,_X___X__,
  ____X___,_X___X__,
  ___X____,_X___X__,
  ___X____,_X___X__,
  __XX_X__,_X___X__,
  _X_XX___,_X___X__,
  X__X_X__,_X___X__,
  ___X_X__,_X___X__,
  ___X____,X____X__,
  ___X____,X____X__,
  ___X___X,_____X__,
  ___X__X_,__X_X___,
  ___X_X__,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5236[ 32] = { /* code 5236 */
  _____X__,_____X__,
  __X__X__,_____X__,
  __X__X__,_____X__,
  __XXXXXX,X_X__X__,
  _X___X__,__X__X__,
  _____X__,__X__X__,
  XXXXXXXX,XXX__X__,
  _____X__,__X__X__,
  _____X__,__X__X__,
  __XXXXXX,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__XX_,X____X__,
  __X__X_X,_____X__,
  _____X__,___X_X__,
  _____X__,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_529F[ 32] = { /* code 529F */
  ________,_X______,
  ________,_X______,
  ________,_X______,
  XXXXXXX_,_X______,
  ___X___X,XXXXXX__,
  ___X____,_X___X__,
  ___X____,_X___X__,
  ___X____,_X___X__,
  ___X____,_X___X__,
  ___X____,X____X__,
  ___X____,X____X__,
  ___XXXX_,X____X__,
  XXXX___X,_____X__,
  _X_____X,_____X__,
  ______X_,__X_X___,
  _____X__,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5305[ 32] = { /* code 5305 */
  ____X___,________,
  ____X___,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  __X_____,___X____,
  _X_XXXXX,X__X____,
  X__X____,X__X____,
  ___X____,X__X____,
  ___X____,X__X____,
  ___XXXXX,X__X____,
  ___X____,_X_X____,
  ___X____,__X_____,
  ___X____,_____X__,
  ___X____,_____X__,
  ____XXXX,XXXXXX__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5316[ 32] = { /* code 5316 */
  ____X___,X_______,
  ____X___,X_______,
  ____X___,X____X__,
  ___X____,X___X___,
  ___X____,X__X____,
  __XX____,X_X_____,
  __XX____,XX______,
  _X_X____,X_______,
  X__X___X,X_______,
  ___X__X_,X_______,
  ___X_X__,X_______,
  ___X____,X_____X_,
  ___X____,X_____X_,
  ___X____,X_____X_,
  ___X____,_XXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_533A[ 32] = { /* code 533A */
  ________,________,
  _XXXXXXX,XXXXXX__,
  _X______,________,
  _X______,___X____,
  _X___X__,___X____,
  _X____X_,__X_____,
  _X_____X,_X______,
  _X______,X_______,
  _X_____X,_X______,
  _X____X_,__X_____,
  _X___X__,___X____,
  _X__X___,___X____,
  _X______,________,
  _X______,________,
  _XXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5341[ 32] = { /* code 5341 */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_534F[ 32] = { /* code 534F */
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  XXXXX_XX,XXXX____,
  __X_____,X__X____,
  __X_____,X__X____,
  __X___X_,X__XX___,
  __X___X_,X__X_X__,
  __X__X__,X__X__X_,
  __X_X___,X__X__X_,
  __X_____,X__X____,
  __X____X,___X____,
  __X____X,___X____,
  __X___X_,_X_X____,
  __X__X__,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5361[ 32] = { /* code 5361 */
  ______X_,________,
  ______X_,________,
  ______XX,XXXXX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,________,
  ______X_,________,
  ______X_,_X______,
  ______X_,__X_____,
  ______X_,___X____,
  ______X_,____X___,
  ______X_,________,
  ______X_,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_53E3[ 32] = { /* code 53E3 */
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_53F7[ 32] = { /* code 53F7 */
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ____X___,________,
  ___X____,________,
  ___XXXXX,XXXX____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,X_X_____,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5524[ 32] = { /* code 5524 */
  _______X,________,
  _______X,________,
  XXXX___X,XXXX____,
  X__X__X_,___X____,
  X__X_X__,__X_____,
  X__XX_XX,XXXXX___,
  X__X__X_,_X__X___,
  X__X__X_,_X__X___,
  X__X__X_,_X__X___,
  X__X__X_,_X__X___,
  XXXX_XXX,XXXXXXX_,
  X__X____,X_X_____,
  ________,X_X_____,
  _______X,___X____,
  ______X_,____X___,
  ____XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5730[ 32] = { /* code 5730 */
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X___X,__X_____,
  ___X___X,__X_XX__,
  XXXXXX_X,__XX_X__,
  ___X___X,_XX__X__,
  ___X__XX,X_X__X__,
  ___X___X,__X__X__,
  ___X___X,__XX_X__,
  ___X___X,__X_X___,
  ___XXX_X,__X___X_,
  XXX____X,__X___X_,
  _X_____X,______X_,
  ________,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5740[ 32] = { /* code 5740 */
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X___X,__X_____,
  ___X___X,__X_____,
  XXXXXX_X,__X_____,
  ___X___X,__XXXX__,
  ___X___X,__X_____,
  ___X___X,__X_____,
  ___X___X,__X_____,
  ___X___X,__X_____,
  ___XXX_X,__X_____,
  XXX____X,__X_____,
  _X_____X,__X_____,
  _____XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5757[ 32] = { /* code 5757 */
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X__XX,XXXXXX__,
  ___X____,_X___X__,
  XXXXXX__,_X___X__,
  ___X____,_X___X__,
  ___X____,_X___X__,
  ___X__XX,XXXXXXX_,
  ___X____,_X______,
  ___X____,X_X_____,
  ___XXX__,X_X_____,
  XXX____X,___X____,
  _X____X_,____X___,
  _____X__,_____X__,
  ____X___,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5931[ 32] = { /* code 5931 */
  _______X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  __XXXXXX,XXXXX___,
  __X____X,________,
  _X_____X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,____X___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_59CB[ 32] = { /* code 59CB */
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,_X______,
  XXXXXX__,_X__X___,
  __X__X__,X____X__,
  __X__X_X,XXXXXXX_,
  __X__X__,X_____X_,
  __X__X__,________,
  _X__X___,XXXXXX__,
  __X_X___,X____X__,
  ___X____,X____X__,
  __X_X___,X____X__,
  _X___X__,X____X__,
  X_______,XXXXXX__,
  ________,X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5B58[ 32] = { /* code 5B58 */
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXXXXXX_,
  ____X___,________,
  ____X___,________,
  ___X__XX,XXXXX___,
  ___X____,___X____,
  __XX____,__X_____,
  _X_X____,_X______,
  X__X_XXX,XXXXXXX_,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X___X,_X______,
  ___X____,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5BC6[ 32] = { /* code 5BC6 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_____X_,__X__X__,
  ____X__X,_X______,
  __X_X___,X___X___,
  _X__X_XX,___X_X__,
  ___XXX__,___X____,
  XXX__XXX,XXXX____,
  _______X,________,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5BFB[ 32] = { /* code 5BFB */
  ________,________,
  __XXXXXX,XXXXX___,
  ________,____X___,
  ________,____X___,
  ___XXXXX,XXXXX___,
  ________,____X___,
  ________,____X___,
  __XXXXXX,XXXXX___,
  ________,__X_____,
  ________,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  _____X__,__X_____,
  _____X__,__X_____,
  ________,X_X_____,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6210[ 32] = { /* code 6210 */
  ________,_X_X____,
  ________,_X__X___,
  ________,_X______,
  __XXXXXX,XXXXXXX_,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X___X__,
  __XXXXX_,_X___X__,
  __X___X_,_X___X__,
  __X___X_,__X_X___,
  __X___X_,__X_X___,
  __X___X_,___X__X_,
  __X_X_X_,__XX__X_,
  _X___X__,_X__X_X_,
  _X______,X____XX_,
  X______X,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6247[ 32] = { /* code 6247 */
  ______X_,________,
  _______X,________,
  __XXXXXX,XXXXXX__,
  __X_____,_____X__,
  __X_____,_____X__,
  __XXXXXX,XXXXXX__,
  __X_____,________,
  __X_____,________,
  __XXXXXX,_XXXXX__,
  __X____X,_____X__,
  __X_X__X,__X__X__,
  __X__X_X,___X_X__,
  _X__X__X,__X__X__,
  _X_X___X,_X___X__,
  X____X_X,___X_X__,
  ______X_,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6263[ 32] = { /* code 6263 */
  ___X____,________,
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X___X,_____X__,
  XXXXXX_X,_____X__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X_X_X,_____X__,
  ___XX__X,_____X__,
  __XX___X,_____X__,
  XX_X___X,_____X__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X___X,XXXXXX__,
  _X_X___X,_____X__,
  __X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_636E[ 32] = { /* code 636E */
  __X_____,________,
  __X___XX,XXXXXX__,
  __X___X_,_____X__,
  __X___X_,_____X__,
  XXXXX_XX,XXXXXX__,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X_X_XX,XXXXXXX_,
  __XX__X_,__X_____,
  XXX___X_,__X_____,
  __X___X_,XXXXXX__,
  __X___X_,X____X__,
  __X___X_,X____X__,
  __X__X__,X____X__,
  X_X__X__,XXXXXX__,
  _X__X___,X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_63D0[ 32] = { /* code 63D0 */
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  XXXXXX_X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X_X_X,XXXXXX__,
  ___XX___,________,
  __XX__XX,XXXXXXX_,
  XX_X____,__X_____,
  ___X___X,__X_____,
  ___X___X,__XXXX__,
  ___X___X,__X_____,
  _X_X__X_,X_X_____,
  __X__X__,_XXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_64CD[ 32] = { /* code 64CD */
  __X___XX,XXXXX___,
  __X___X_,____X___,
  __X___X_,____X___,
  __X___XX,XXXXX___,
  XXXXX___,________,
  __X__XXX,X_XXXX__,
  __X__X__,X_X__X__,
  __X_XX__,X_X__X__,
  __XX_XXX,X_XXXX__,
  XXX_____,_X______,
  __X_XXXX,XXXXXXX_,
  __X____X,_XX_____,
  __X___X_,_X_X____,
  __X__X__,_X__X___,
  X_XXX___,_X___XX_,
  _X______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6570[ 32] = { /* code 6570 */
  ____X___,__X_____,
  _X__X__X,__X_____,
  __X_X_X_,__X_____,
  ____X___,__XXXXX_,
  XXXXXXXX,_X___X__,
  __X_X_X_,_X___X__,
  _X__X__X,_X___X__,
  X___X___,X_X__X__,
  ___X____,__X_X___,
  XXXXXXX_,__X_X___,
  __X___X_,___X____,
  _X____X_,___X____,
  _XX__X__,__X_X___,
  ___XX___,__X_X___,
  __XX_X__,_X___X__,
  XX____X_,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_663E[ 32] = { /* code 663E */
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  _____X__,_X______,
  _X___X__,_X___X__,
  __X__X__,_X___X__,
  ___X_X__,_X__X___,
  ___X_X__,_X_X____,
  _____X__,_X______,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6807[ 32] = { /* code 6807 */
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X____,________,
  ___X____,________,
  XXXXXX__,________,
  ___X__XX,XXXXXXX_,
  __XX____,__X_____,
  __XXX___,__X_____,
  _X_X_X_X,__X_X___,
  _X_X_X_X,__X__X__,
  X__X__X_,__X__X__,
  ___X__X_,__X___X_,
  ___X_X__,__X___X_,
  ___X____,__X_____,
  ___X____,X_X_____,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6B3E[ 32] = { /* code 6B3E */
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,__X_____,
  ____X___,_XXXXXX_,
  ____X___,_X____X_,
  _XXXXXX_,X____X__,
  ________,___X____,
  _XXXXXX_,___X____,
  ________,___X____,
  XXXXXXXX,___X____,
  ____X___,__X_X___,
  _X__X_X_,__X_X___,
  _X__X__X,_X__X___,
  X___X__X,_X___X__,
  __X_X___,X____X__,
  ___X___X,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_7720[ 32] = { /* code 7720 */
  ________,________,
  _______X,XXXXXX__,
  _XXXXX_X,_____X__,
  _X___X_X,_____X__,
  _X___X_X,_____X__,
  _XXXXX_X,XXXXXX__,
  _X___X_X,__X_____,
  _X___X_X,__X_____,
  _XXXXX_X,XXXXXXX_,
  _X___X_X,__X_____,
  _X___X_X,__X_____,
  _X___X_X,___X____,
  _XXXXX_X,___X__X_,
  _X___X_X,_X__X_X_,
  _______X,X____XX_,
  _______X,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_793A[ 32] = { /* code 793A */
  ________,________,
  __XXXXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  ___X___X,___X____,
  ___X___X,____X___,
  __X____X,_____X__,
  _X_____X,______X_,
  X______X,______X_,
  _____X_X,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_7A97[ 32] = { /* code 7A97 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X__X___,__X___X_,
  X__X__X_,___X_X__,
  _____X__,________,
  __XXXXXX,XXXXX___,
  __X___X_,____X___,
  __X___XX,XX__X___,
  __X__X__,_X__X___,
  __X_X_X_,X___X___,
  __X____X,____X___,
  __X___X_,X___X___,
  __X__X__,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_7B7E[ 32] = { /* code 7B7E */
  ___X____,_X______,
  ___X____,_X______,
  __XXXXXX,_XXXXXX_,
  __X_X___,X__X____,
  _X___X_X,____X___,
  X_____X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  __XX_XXX,XX_XX___,
  XX______,_____XX_,
  ______X_,___X____,
  ___X___X,___X____,
  ____X__X,__X_____,
  ____X___,_X______,
  _XXXXXXX,XXXXXX__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_80FD[ 32] = { /* code 80FD */
  ___X____,_X______,
  __X__X__,_X___X__,
  _X____X_,_X__X___,
  XXXXXXXX,_XXX____,
  _______X,_X______,
  ________,_X____X_,
  _XXXXXX_,_X____X_,
  _X____X_,__XXXXX_,
  _X____X_,________,
  _XXXXXX_,_X___X__,
  _X____X_,_X__X___,
  _X____X_,_XXX____,
  _XXXXXX_,_X______,
  _X____X_,_X____X_,
  _X__X_X_,_X____X_,
  _X___X__,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_8BAE[ 32] = { /* code 8BAE */
  ________,X_______,
  __X_____,_X__X___,
  ___X__X_,_X__X___,
  ___X__X_,____X___,
  ______X_,____X___,
  _______X,___X____,
  XXXX___X,___X____,
  ___X___X,___X____,
  ___X____,X_X_____,
  ___X____,X_X_____,
  ___X____,_X______,
  ___X_X__,_X______,
  ___XX___,X_X_____,
  ___X___X,___X____,
  ______X_,____X___,
  ____XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_8BFB[ 32] = { /* code 8BFB */
  ________,__X_____,
  __X_____,__X_____,
  ___X___X,XXXXXX__,
  ___X____,__X_____,
  ________,__X_____,
  ______XX,XXXXXXX_,
  XXXX____,______X_,
  ___X____,X__X_X__,
  ___X____,_X_X____,
  ___X___X,___X____,
  ___X____,X__X____,
  ___X__XX,XXXXXXX_,
  ___X_X__,__X_X___,
  ___XX___,_X___X__,
  ___X____,X_____X_,
  ______XX,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_8D25[ 32] = { /* code 8D25 */
  ________,_X______,
  _XXXXX__,_X______,
  _X___X__,_X______,
  _X_X_X__,X_______,
  _X_X_X__,XXXXXXX_,
  _X_X_X_X,____X___,
  _X_X_XX_,X___X___,
  _X_X_X__,X___X___,
  _X_X_X__,X___X___,
  _X_X_X__,_X_X____,
  _X_X_X__,_X_X____,
  ___X____,__X_____,
  __X_X___,_X_X____,
  __X__X__,X___X___,
  _X___X_X,_____X__,
  X_____X_,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_8FDB[ 32] = { /* code 8FDB */
  ________,X__X____,
  __X_____,X__X____,
  ___X____,X__X____,
  ___X__XX,XXXXXX__,
  ________,X__X____,
  ________,X__X____,
  XXXX____,X__X____,
  ___X_XXX,XXXXXXX_,
  ___X____,X__X____,
  ___X____,X__X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X__X_,___X____,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_9192[ 32] = { /* code 9192 */
  ________,________,
  XXXXXXX_,_XXXXX__,
  __X_X___,_X___X__,
  __X_X___,_XXXXX__,
  XXXXXXX_,_X___X__,
  X_X_X_X_,_XXXXX__,
  X_X_X_X_,___X____,
  X_X_X_X_,_X_X____,
  X_X_XXX_,_XXXXX__,
  XX____X_,X__X____,
  X_____X_,___X____,
  XXXXXXX_,_XXXXX__,
  X_____X_,___X____,
  X_____X_,___X____,
  XXXXXXX_,XXXXXXX_,
  X_____X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_91D1[ 32] = { /* code 91D1 */
  _______X,________,
  _______X,________,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,___X____,
  __X_XXXX,XXX_X___,
  XX_____X,_____XX_,
  _______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  ___X___X,___X____,
  ____X__X,___X____,
  ____X__X,__X_____,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_94A5[ 32] = { /* code 94A5 */
  ___X____,________,
  ___X____,XXXXXX__,
  __XXXX__,X____X__,
  __X_____,X____X__,
  _X______,X____X__,
  X_XXXX__,XXXXXX__,
  ___X____,X____X__,
  ___X____,X____X__,
  XXXXXX__,X____X__,
  ___X____,XXXXXX__,
  ___X____,X____X__,
  ___X____,X____X__,
  ___X_X_X,_____X__,
  ___XX__X,_____X__,
  ___X__X_,___X_X__,
  _____X__,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_94B1[ 32] = { /* code 94B1 */
  ___X____,_X_X____,
  ___X____,_X__X___,
  __XXXX__,_X______,
  __X_____,_X_XXX__,
  _X_____X,XXX_____,
  X_XXXX__,_X______,
  ___X____,_X_XXXX_,
  ___X___X,XXX_____,
  XXXXXX__,_X___X__,
  ___X____,_X__X___,
  ___X____,__XX____,
  ___X____,__X___X_,
  ___X_X__,_X_X__X_,
  ___XX___,X___X_X_,
  ___X__XX,_____XX_,
  ________,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_989D[ 32] = { /* code 989D */
  ___X____,________,
  ____X___,XXXXXXX_,
  _XXXXXXX,___X____,
  _X_____X,__X_____,
  ___X____,_XXXXX__,
  ___XXXX_,_X___X__,
  __X___X_,_X_X_X__,
  _X_X_X__,_X_X_X__,
  ____X___,_X_X_X__,
  ___X_X__,_X_X_X__,
  __X___X_,_X_X_X__,
  _XXXXXXX,_X_X_X__,
  X_X___X_,__X_X___,
  __X___X_,__X__X__,
  __XXXXX_,_X____X_,
  __X___X_,X_____X_};

/* Start of unicode area <Halfwidth and Fullwidth Forms> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_FF08[ 32] = { /* code FF08, FULLWIDTH LEFT PARENTHESIS */
  ________,________,
  ________,____X___,
  ________,___X____,
  ________,__X_____,
  ________,__X_____,
  ________,_X______,
  ________,_X______,
  ________,_X______,
  ________,_X______,
  ________,_X______,
  ________,_X______,
  ________,__X_____,
  ________,__X_____,
  ________,___X____,
  ________,____X___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_FF09[ 32] = { /* code FF09, FULLWIDTH RIGHT PARENTHESIS */
  ________,________,
  __X_____,________,
  ___X____,________,
  ____X___,________,
  ____X___,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ___X____,________,
  __X_____,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_FF1A[ 32] = { /* code FF1A, FULLWIDTH COLON */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XX____,________,
  __XX____,________,
  ________,________,
  __XX____,________,
  __XX____,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFontSong_CharInfo[83] = {
   {   8,   8,  1, acGUI_FontFontSong_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_FontFontSong_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_FontFontSong_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_FontFontSong_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_FontFontSong_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_FontFontSong_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_FontFontSong_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_FontFontSong_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_FontFontSong_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_FontFontSong_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_FontFontSong_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_FontFontSong_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_FontFontSong_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_FontFontSong_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_FontFontSong_0044 } /* code 0044 */
  ,{   8,   8,  1, acGUI_FontFontSong_0045 } /* code 0045 */
  ,{   8,   8,  1, acGUI_FontFontSong_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_FontFontSong_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_FontFontSong_004C } /* code 004C */
  ,{   8,   8,  1, acGUI_FontFontSong_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_FontFontSong_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_FontFontSong_0055 } /* code 0055 */
  ,{   8,   8,  1, acGUI_FontFontSong_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_FontFontSong_0063 } /* code 0063 */
  ,{   8,   8,  1, acGUI_FontFontSong_0065 } /* code 0065 */
  ,{   8,   8,  1, acGUI_FontFontSong_006B } /* code 006B */
  ,{   8,   8,  1, acGUI_FontFontSong_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_FontFontSong_0073 } /* code 0073 */
  ,{  16,  16,  2, acGUI_FontFontSong_4F11 } /* code 4F11 */
  ,{  16,  16,  2, acGUI_FontFontSong_4F59 } /* code 4F59 */
  ,{  16,  16,  2, acGUI_FontFontSong_4F5C } /* code 4F5C */
  ,{  16,  16,  2, acGUI_FontFontSong_503C } /* code 503C */
  ,{  16,  16,  2, acGUI_FontFontSong_5145 } /* code 5145 */
  ,{  16,  16,  2, acGUI_FontFontSong_516D } /* code 516D */
  ,{  16,  16,  2, acGUI_FontFontSong_5185 } /* code 5185 */
  ,{  16,  16,  2, acGUI_FontFontSong_5199 } /* code 5199 */
  ,{  16,  16,  2, acGUI_FontFontSong_521D } /* code 521D */
  ,{  16,  16,  2, acGUI_FontFontSong_5236 } /* code 5236 */
  ,{  16,  16,  2, acGUI_FontFontSong_529F } /* code 529F */
  ,{  16,  16,  2, acGUI_FontFontSong_5305 } /* code 5305 */
  ,{  16,  16,  2, acGUI_FontFontSong_5316 } /* code 5316 */
  ,{  16,  16,  2, acGUI_FontFontSong_533A } /* code 533A */
  ,{  16,  16,  2, acGUI_FontFontSong_5341 } /* code 5341 */
  ,{  16,  16,  2, acGUI_FontFontSong_534F } /* code 534F */
  ,{  16,  16,  2, acGUI_FontFontSong_5361 } /* code 5361 */
  ,{  16,  16,  2, acGUI_FontFontSong_53E3 } /* code 53E3 */
  ,{  16,  16,  2, acGUI_FontFontSong_53F7 } /* code 53F7 */
  ,{  16,  16,  2, acGUI_FontFontSong_5524 } /* code 5524 */
  ,{  16,  16,  2, acGUI_FontFontSong_5730 } /* code 5730 */
  ,{  16,  16,  2, acGUI_FontFontSong_5740 } /* code 5740 */
  ,{  16,  16,  2, acGUI_FontFontSong_5757 } /* code 5757 */
  ,{  16,  16,  2, acGUI_FontFontSong_5931 } /* code 5931 */
  ,{  16,  16,  2, acGUI_FontFontSong_59CB } /* code 59CB */
  ,{  16,  16,  2, acGUI_FontFontSong_5B58 } /* code 5B58 */
  ,{  16,  16,  2, acGUI_FontFontSong_5BC6 } /* code 5BC6 */
  ,{  16,  16,  2, acGUI_FontFontSong_5BFB } /* code 5BFB */
  ,{  16,  16,  2, acGUI_FontFontSong_6210 } /* code 6210 */
  ,{  16,  16,  2, acGUI_FontFontSong_6247 } /* code 6247 */
  ,{  16,  16,  2, acGUI_FontFontSong_6263 } /* code 6263 */
  ,{  16,  16,  2, acGUI_FontFontSong_636E } /* code 636E */
  ,{  16,  16,  2, acGUI_FontFontSong_63D0 } /* code 63D0 */
  ,{  16,  16,  2, acGUI_FontFontSong_64CD } /* code 64CD */
  ,{  16,  16,  2, acGUI_FontFontSong_6570 } /* code 6570 */
  ,{  16,  16,  2, acGUI_FontFontSong_663E } /* code 663E */
  ,{  16,  16,  2, acGUI_FontFontSong_6807 } /* code 6807 */
  ,{  16,  16,  2, acGUI_FontFontSong_6B3E } /* code 6B3E */
  ,{  16,  16,  2, acGUI_FontFontSong_7720 } /* code 7720 */
  ,{  16,  16,  2, acGUI_FontFontSong_793A } /* code 793A */
  ,{  16,  16,  2, acGUI_FontFontSong_7A97 } /* code 7A97 */
  ,{  16,  16,  2, acGUI_FontFontSong_7B7E } /* code 7B7E */
  ,{  16,  16,  2, acGUI_FontFontSong_80FD } /* code 80FD */
  ,{  16,  16,  2, acGUI_FontFontSong_8BAE } /* code 8BAE */
  ,{  16,  16,  2, acGUI_FontFontSong_8BFB } /* code 8BFB */
  ,{  16,  16,  2, acGUI_FontFontSong_8D25 } /* code 8D25 */
  ,{  16,  16,  2, acGUI_FontFontSong_8FDB } /* code 8FDB */
  ,{  16,  16,  2, acGUI_FontFontSong_9192 } /* code 9192 */
  ,{  16,  16,  2, acGUI_FontFontSong_91D1 } /* code 91D1 */
  ,{  16,  16,  2, acGUI_FontFontSong_94A5 } /* code 94A5 */
  ,{  16,  16,  2, acGUI_FontFontSong_94B1 } /* code 94B1 */
  ,{  16,  16,  2, acGUI_FontFontSong_989D } /* code 989D */
  ,{  16,  16,  2, acGUI_FontFontSong_FF08 } /* code FF08 */
  ,{  16,  16,  2, acGUI_FontFontSong_FF09 } /* code FF09 */
  ,{  16,  16,  2, acGUI_FontFontSong_FF1A } /* code FF1A */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop68 = {
   0xFF1A /* first character */
  ,0xFF1A /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 82] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop67 = {
   0xFF08 /* first character */
  ,0xFF09 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 80] /* address of first character */
  ,&GUI_FontFontSong_Prop68 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop66 = {
   0x989D /* first character */
  ,0x989D /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 79] /* address of first character */
  ,&GUI_FontFontSong_Prop67 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop65 = {
   0x94B1 /* first character */
  ,0x94B1 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 78] /* address of first character */
  ,&GUI_FontFontSong_Prop66 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop64 = {
   0x94A5 /* first character */
  ,0x94A5 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 77] /* address of first character */
  ,&GUI_FontFontSong_Prop65 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop63 = {
   0x91D1 /* first character */
  ,0x91D1 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 76] /* address of first character */
  ,&GUI_FontFontSong_Prop64 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop62 = {
   0x9192 /* first character */
  ,0x9192 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 75] /* address of first character */
  ,&GUI_FontFontSong_Prop63 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop61 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 74] /* address of first character */
  ,&GUI_FontFontSong_Prop62 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop60 = {
   0x8D25 /* first character */
  ,0x8D25 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 73] /* address of first character */
  ,&GUI_FontFontSong_Prop61 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop59 = {
   0x8BFB /* first character */
  ,0x8BFB /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 72] /* address of first character */
  ,&GUI_FontFontSong_Prop60 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop58 = {
   0x8BAE /* first character */
  ,0x8BAE /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 71] /* address of first character */
  ,&GUI_FontFontSong_Prop59 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop57 = {
   0x80FD /* first character */
  ,0x80FD /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 70] /* address of first character */
  ,&GUI_FontFontSong_Prop58 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop56 = {
   0x7B7E /* first character */
  ,0x7B7E /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 69] /* address of first character */
  ,&GUI_FontFontSong_Prop57 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop55 = {
   0x7A97 /* first character */
  ,0x7A97 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 68] /* address of first character */
  ,&GUI_FontFontSong_Prop56 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop54 = {
   0x793A /* first character */
  ,0x793A /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 67] /* address of first character */
  ,&GUI_FontFontSong_Prop55 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop53 = {
   0x7720 /* first character */
  ,0x7720 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 66] /* address of first character */
  ,&GUI_FontFontSong_Prop54 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop52 = {
   0x6B3E /* first character */
  ,0x6B3E /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 65] /* address of first character */
  ,&GUI_FontFontSong_Prop53 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop51 = {
   0x6807 /* first character */
  ,0x6807 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 64] /* address of first character */
  ,&GUI_FontFontSong_Prop52 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop50 = {
   0x663E /* first character */
  ,0x663E /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 63] /* address of first character */
  ,&GUI_FontFontSong_Prop51 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop49 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 62] /* address of first character */
  ,&GUI_FontFontSong_Prop50 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop48 = {
   0x64CD /* first character */
  ,0x64CD /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 61] /* address of first character */
  ,&GUI_FontFontSong_Prop49 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop47 = {
   0x63D0 /* first character */
  ,0x63D0 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 60] /* address of first character */
  ,&GUI_FontFontSong_Prop48 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop46 = {
   0x636E /* first character */
  ,0x636E /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 59] /* address of first character */
  ,&GUI_FontFontSong_Prop47 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop45 = {
   0x6263 /* first character */
  ,0x6263 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 58] /* address of first character */
  ,&GUI_FontFontSong_Prop46 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop44 = {
   0x6247 /* first character */
  ,0x6247 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 57] /* address of first character */
  ,&GUI_FontFontSong_Prop45 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop43 = {
   0x6210 /* first character */
  ,0x6210 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 56] /* address of first character */
  ,&GUI_FontFontSong_Prop44 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop42 = {
   0x5BFB /* first character */
  ,0x5BFB /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 55] /* address of first character */
  ,&GUI_FontFontSong_Prop43 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop41 = {
   0x5BC6 /* first character */
  ,0x5BC6 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 54] /* address of first character */
  ,&GUI_FontFontSong_Prop42 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop40 = {
   0x5B58 /* first character */
  ,0x5B58 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 53] /* address of first character */
  ,&GUI_FontFontSong_Prop41 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop39 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 52] /* address of first character */
  ,&GUI_FontFontSong_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop38 = {
   0x5931 /* first character */
  ,0x5931 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 51] /* address of first character */
  ,&GUI_FontFontSong_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop37 = {
   0x5757 /* first character */
  ,0x5757 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 50] /* address of first character */
  ,&GUI_FontFontSong_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop36 = {
   0x5740 /* first character */
  ,0x5740 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 49] /* address of first character */
  ,&GUI_FontFontSong_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop35 = {
   0x5730 /* first character */
  ,0x5730 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 48] /* address of first character */
  ,&GUI_FontFontSong_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop34 = {
   0x5524 /* first character */
  ,0x5524 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 47] /* address of first character */
  ,&GUI_FontFontSong_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop33 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 46] /* address of first character */
  ,&GUI_FontFontSong_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop32 = {
   0x53E3 /* first character */
  ,0x53E3 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 45] /* address of first character */
  ,&GUI_FontFontSong_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop31 = {
   0x5361 /* first character */
  ,0x5361 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 44] /* address of first character */
  ,&GUI_FontFontSong_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop30 = {
   0x534F /* first character */
  ,0x534F /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 43] /* address of first character */
  ,&GUI_FontFontSong_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop29 = {
   0x5341 /* first character */
  ,0x5341 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 42] /* address of first character */
  ,&GUI_FontFontSong_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop28 = {
   0x533A /* first character */
  ,0x533A /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 41] /* address of first character */
  ,&GUI_FontFontSong_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop27 = {
   0x5316 /* first character */
  ,0x5316 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 40] /* address of first character */
  ,&GUI_FontFontSong_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop26 = {
   0x5305 /* first character */
  ,0x5305 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 39] /* address of first character */
  ,&GUI_FontFontSong_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop25 = {
   0x529F /* first character */
  ,0x529F /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 38] /* address of first character */
  ,&GUI_FontFontSong_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop24 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 37] /* address of first character */
  ,&GUI_FontFontSong_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop23 = {
   0x521D /* first character */
  ,0x521D /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 36] /* address of first character */
  ,&GUI_FontFontSong_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop22 = {
   0x5199 /* first character */
  ,0x5199 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 35] /* address of first character */
  ,&GUI_FontFontSong_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop21 = {
   0x5185 /* first character */
  ,0x5185 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 34] /* address of first character */
  ,&GUI_FontFontSong_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop20 = {
   0x516D /* first character */
  ,0x516D /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 33] /* address of first character */
  ,&GUI_FontFontSong_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop19 = {
   0x5145 /* first character */
  ,0x5145 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 32] /* address of first character */
  ,&GUI_FontFontSong_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop18 = {
   0x503C /* first character */
  ,0x503C /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 31] /* address of first character */
  ,&GUI_FontFontSong_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop17 = {
   0x4F5C /* first character */
  ,0x4F5C /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 30] /* address of first character */
  ,&GUI_FontFontSong_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop16 = {
   0x4F59 /* first character */
  ,0x4F59 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 29] /* address of first character */
  ,&GUI_FontFontSong_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop15 = {
   0x4F11 /* first character */
  ,0x4F11 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 28] /* address of first character */
  ,&GUI_FontFontSong_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop14 = {
   0x0073 /* first character */
  ,0x0073 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 27] /* address of first character */
  ,&GUI_FontFontSong_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop13 = {
   0x0070 /* first character */
  ,0x0070 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 26] /* address of first character */
  ,&GUI_FontFontSong_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop12 = {
   0x006B /* first character */
  ,0x006B /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 25] /* address of first character */
  ,&GUI_FontFontSong_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop11 = {
   0x0065 /* first character */
  ,0x0065 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 24] /* address of first character */
  ,&GUI_FontFontSong_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop10 = {
   0x0063 /* first character */
  ,0x0063 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 23] /* address of first character */
  ,&GUI_FontFontSong_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop9 = {
   0x0061 /* first character */
  ,0x0061 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 22] /* address of first character */
  ,&GUI_FontFontSong_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop8 = {
   0x0055 /* first character */
  ,0x0055 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 21] /* address of first character */
  ,&GUI_FontFontSong_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop7 = {
   0x0053 /* first character */
  ,0x0053 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 20] /* address of first character */
  ,&GUI_FontFontSong_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop6 = {
   0x004F /* first character */
  ,0x004F /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 19] /* address of first character */
  ,&GUI_FontFontSong_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop5 = {
   0x004C /* first character */
  ,0x004C /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 18] /* address of first character */
  ,&GUI_FontFontSong_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop4 = {
   0x0049 /* first character */
  ,0x0049 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 17] /* address of first character */
  ,&GUI_FontFontSong_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop3 = {
   0x0041 /* first character */
  ,0x0046 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFontSong_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop2 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  1] /* address of first character */
  ,&GUI_FontFontSong_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop1 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontFontSong_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontSong_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontSong_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

