/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (NXP) version 5.38                     *
*        Compiled Nov 24 2016, 16:56:53                              *
*                                                                    *
*        (c) 1998 - 2016 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FONT3.c                                               *
* Font:        ËÎÌו                                                  *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  20                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        8BA1 - 8BA1                                  *
* Range enabled:        6570 - 6570                                  *
* Range enabled:        6E05 - 6E05                                  *
* Range enabled:        96F6 - 96F6                                  *
* Range enabled:        5361 - 5361                                  *
* Range enabled:        53F7 - 53F7                                  *
* Range enabled:        9664 - 9664                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFONT3;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFONT3_5361[ 60] = { /* code 5361 */
  ________,________,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX_____X,________,
  ________,XXXXXXXX,X_______,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,_X______,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ________,XX______,________,
  ________,XX______,________,
  ________,XXXX____,________,
  ________,XX__XXX_,________,
  ________,XX____XX,________,
  ________,XX_____X,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,X_______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFONT3_53F7[ 60] = { /* code 53F7 */
  ________,________,________,
  _____X__,______X_,________,
  _____XXX,XXXXXXX_,________,
  _____X__,______X_,________,
  _____X__,______X_,________,
  _____X__,______X_,________,
  _____XXX,XXXXXXX_,________,
  _____X__,________,________,
  ________,________,XX______,
  __XXXXXX,XXXXXXXX,________,
  _______X,________,________,
  ______X_,_______X,________,
  ______XX,XXXXXXXX,________,
  ________,______X_,________,
  ________,______X_,________,
  ________,______X_,________,
  ________,_____XX_,________,
  ________,_XXXXX__,________,
  ________,___XX___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFONT3_6570[ 60] = { /* code 6570 */
  ________,________,________,
  ______X_,____XX__,________,
  ___X__X_,_X__XX__,________,
  ___XX_X_,X___X___,________,
  ____X_X_,____X___,________,
  ______X_,_XXX____,_XX_____,
  __XXXXXX,X__XXXXX,X_______,
  ____X_X_,X_XX____,X_______,
  ___X__X_,_XX_X__X,X_______,
  __X___X_,_X__X__X,________,
  _X___XX_,____X__X,________,
  _____X__,_X__X__X,________,
  __XXXXXX,XX___X_X,________,
  ____X___,X____XX_,________,
  ____XX_X,______X_,________,
  ______XX,XX___XXX,________,
  _____X__,_X__X__X,X_______,
  ___XX___,__XX____,XXX_____,
  _XX_____,XX______,_X______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFONT3_6E05[ 60] = { /* code 6E05 */
  ________,________,________,
  __X_____,____X___,________,
  ___XX___,____X___,________,
  ____X__X,XXXXXXXX,XX______,
  ____X___,____X__X,________,
  ________,XXXXXXXX,X_______,
  _XX__X__,____X___,________,
  __XX_X__,____X___,_X______,
  ___XX_XX,XXXX_XXX,X_______,
  ____X___,________,X_______,
  ____X___,XXXXXXXX,X_______,
  ____X___,X_______,X_______,
  ___X____,XXXXXXXX,X_______,
  _XXX____,X_______,X_______,
  ___X____,XXXXXXXX,X_______,
  ___X____,X_______,X_______,
  __XX____,X_______,X_______,
  __XX____,X____XXX,X_______,
  ________,X______X,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFONT3_8BA1[ 60] = { /* code 8BA1 */
  ________,________,________,
  ___X____,____X___,________,
  ____X___,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  ________,____X___,________,
  ________,____X___,________,
  ____X___,____X___,_X______,
  __XXX__X,XXXXXXXX,X_______,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____X__X,____X___,________,
  ____X_X_,____X___,________,
  ____XX__,____X___,________,
  ____X___,____X___,________,
  ________,____X___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFONT3_9664[ 60] = { /* code 9664 */
  ________,________,________,
  ________,____X___,________,
  __XXXXXX,___XX___,________,
  __X___X_,___X_X__,________,
  __X__X__,__X___X_,________,
  __X__X__,_X_____X,________,
  __X_X___,_X______,XX______,
  __X_X__X,X_____XX,_X______,
  __X__XX_,__XXXX__,________,
  __X___X_,____X___,________,
  __X___X_,____X___,X_______,
  __X___X_,XXXXXXXX,________,
  __X___X_,____X___,________,
  __XXXXX_,_XX_X_X_,________,
  __X_____,XX__X__X,X_______,
  __X_____,X___X___,XX______,
  __X____X,____X___,_X______,
  __X___X_,__XXX___,________,
  __X_____,___X____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFONT3_96F6[ 60] = { /* code 96F6 */
  ________,________,________,
  ________,______XX,________,
  _____XXX,XXXXXX__,________,
  ________,_X______,_X______,
  __XXXXXX,XXXXXXXX,XX______,
  __X_____,_X______,X_______,
  __X__XX_,_XX__XXX,________,
  ________,_X______,________,
  _____XX_,_XX__XX_,________,
  ________,X_X_____,________,
  ______XX,X__XX___,________,
  ____XX__,_XX__XXX,X_______,
  __XX____,__X_____,XX______,
  ____XXXX,XXXXXXX_,________,
  ________,____XX__,________,
  ______X_,___X____,________,
  _______X,XXX_____,________,
  ________,__XXX___,________,
  ________,____X___,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFONT3_CharInfo[7] = {
   {  20,  20,  3, acGUI_FontFONT3_5361 } /* code 5361 */
  ,{  20,  20,  3, acGUI_FontFONT3_53F7 } /* code 53F7 */
  ,{  20,  20,  3, acGUI_FontFONT3_6570 } /* code 6570 */
  ,{  20,  20,  3, acGUI_FontFONT3_6E05 } /* code 6E05 */
  ,{  20,  20,  3, acGUI_FontFONT3_8BA1 } /* code 8BA1 */
  ,{  20,  20,  3, acGUI_FontFONT3_9664 } /* code 9664 */
  ,{  20,  20,  3, acGUI_FontFONT3_96F6 } /* code 96F6 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFONT3_Prop7 = {
   0x96F6 /* first character */
  ,0x96F6 /* last character  */
  ,&GUI_FontFONT3_CharInfo[  6] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFONT3_Prop6 = {
   0x9664 /* first character */
  ,0x9664 /* last character  */
  ,&GUI_FontFONT3_CharInfo[  5] /* address of first character */
  ,&GUI_FontFONT3_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFONT3_Prop5 = {
   0x8BA1 /* first character */
  ,0x8BA1 /* last character  */
  ,&GUI_FontFONT3_CharInfo[  4] /* address of first character */
  ,&GUI_FontFONT3_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFONT3_Prop4 = {
   0x6E05 /* first character */
  ,0x6E05 /* last character  */
  ,&GUI_FontFONT3_CharInfo[  3] /* address of first character */
  ,&GUI_FontFONT3_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFONT3_Prop3 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontFONT3_CharInfo[  2] /* address of first character */
  ,&GUI_FontFONT3_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFONT3_Prop2 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontFONT3_CharInfo[  1] /* address of first character */
  ,&GUI_FontFONT3_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFONT3_Prop1 = {
   0x5361 /* first character */
  ,0x5361 /* last character  */
  ,&GUI_FontFONT3_CharInfo[  0] /* address of first character */
  ,&GUI_FontFONT3_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFONT3 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFONT3_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

