/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (NXP) version 5.38                     *
*        Compiled Nov 24 2016, 16:56:53                              *
*                                                                    *
*        (c) 1998 - 2016 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FONT1.c                                               *
* Font:        ËÎÌו                                                  *
* Height:      25                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  25                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        6807 - 6807                                  *
* Range enabled:        7B7E - 7B7E                                  *
* Range enabled:        4FE1 - 4FE1                                  *
* Range enabled:        606F - 606F                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFONT1;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFONT1_4FE1[100] = { /* code 4FE1 */
  ________,________,________,________,
  _______X,______X_,________,________,
  ______XX,______XX,________,________,
  ______XX,_______X,X_______,________,
  ______X_,_______X,_____X__,________,
  _____XX_,_XXXXXX_,XXXXX___,________,
  _____X__,________,________,________,
  ____XX__,________,____X___,________,
  ____XX__,__XXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,
  ___X_X__,________,________,________,
  __X__X__,________,____X___,________,
  _X___X__,__XXXXXX,XXXXXX__,________,
  _____X__,________,________,________,
  _____X__,________,____X___,________,
  _____X__,__XXXXXX,XXXXXX__,________,
  _____X__,__XX____,____X___,________,
  _____X__,__XX____,____X___,________,
  _____X__,__XX____,____X___,________,
  _____X__,__XX____,____X___,________,
  _____X__,__XXXXXX,XXXXX___,________,
  _____X__,__XX____,____X___,________,
  _____X__,__X_____,____X___,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFONT1_606F[100] = { /* code 606F */
  ________,________,________,________,
  ________,___XX___,________,________,
  ________,__X_____,__X_____,________,
  ______XX,XXXXXXXX,XXXX____,________,
  ______XX,________,__X_____,________,
  ______XX,________,__X_____,________,
  ______XX,XXXXXXXX,XXX_____,________,
  ______XX,________,__X_____,________,
  ______XX,________,__X_____,________,
  ______XX,________,__X_____,________,
  ______XX,XXXXXXXX,XXX_____,________,
  ______XX,________,__X_____,________,
  ______XX,________,__X_____,________,
  ______XX,XXXXXXXX,XXX_____,________,
  ______X_,___X____,________,________,
  ________,____XX__,________,________,
  ________,XX__XX__,___X____,________,
  ____X___,X____X__,_X__XX__,________,
  ____X___,X_______,_X___XX_,________,
  ___XX___,X_______,_X___XX_,________,
  __XXX___,X_______,_XX___X_,________,
  ________,XXXXXXXX,XXX_____,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFONT1_6807[100] = { /* code 6807 */
  ________,________,________,________,
  _____XX_,________,________,________,
  _____XX_,________,____X___,________,
  _____XX_,___XXXXX,XXXXXX__,________,
  _____XX_,________,________,________,
  _____XX_,________,________,________,
  _____XX_,XX______,________,________,
  __XXXXXX,________,________,________,
  _____XX_,________,_____XX_,________,
  _____XX_,__XXXXXX,XXXXX___,________,
  ____XXXX,________,X_______,________,
  ____XXXX,X_______,X_______,________,
  ____XXX_,XX__X___,X_X_____,________,
  ___X_XX_,X___XX__,X__X____,________,
  ___X_XX_,___XX___,X___X___,________,
  __X__XX_,___X____,X___XX__,________,
  __X__XX_,__XX____,X____X__,________,
  _X___XX_,__X_____,X____XX_,________,
  _____XX_,_X______,X____XX_,________,
  _____XX_,_X______,X_____X_,________,
  _____XX_,X_______,X_______,________,
  _____XX_,_____XXX,X_______,________,
  _____XX_,_______X,X_______,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFONT1_7B7E[100] = { /* code 7B7E */
  ________,________,________,________,
  ______X_,_______X,X_______,________,
  _____XX_,_______X,X_______,________,
  _____XX_,___X___X,_____X__,________,
  _____XXX,XXXXX_XX,XXXXXXX_,________,
  ____X__X,______X_,__X_____,________,
  ___XX___,X____X__,__XX____,________,
  ___X____,XX_XX___,___X____,________,
  __X_____,X__XX___,___X____,________,
  _X______,__XX_X__,________,________,
  ________,_XX___X_,________,________,
  ________,XX_____X,X_______,________,
  _______X,________,XXX_____,________,
  _____XXX,XXXXXXXX,X_XXXXXX,________,
  ___XX___,________,____XX__,________,
  _XX_____,__X_____,_X______,________,
  ______X_,___X____,_XX_____,________,
  _______X,___XX___,XX______,________,
  _______X,X___X___,X_______,________,
  ________,X___X__X,________,________,
  ________,X______X,_____X__,________,
  ___XXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFONT1_CharInfo[4] = {
   {  25,  25,  4, acGUI_FontFONT1_4FE1 } /* code 4FE1 */
  ,{  25,  25,  4, acGUI_FontFONT1_606F } /* code 606F */
  ,{  25,  25,  4, acGUI_FontFONT1_6807 } /* code 6807 */
  ,{  25,  25,  4, acGUI_FontFONT1_7B7E } /* code 7B7E */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFONT1_Prop4 = {
   0x7B7E /* first character */
  ,0x7B7E /* last character  */
  ,&GUI_FontFONT1_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFONT1_Prop3 = {
   0x6807 /* first character */
  ,0x6807 /* last character  */
  ,&GUI_FontFONT1_CharInfo[  2] /* address of first character */
  ,&GUI_FontFONT1_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFONT1_Prop2 = {
   0x606F /* first character */
  ,0x606F /* last character  */
  ,&GUI_FontFONT1_CharInfo[  1] /* address of first character */
  ,&GUI_FontFONT1_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFONT1_Prop1 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_FontFONT1_CharInfo[  0] /* address of first character */
  ,&GUI_FontFONT1_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFONT1 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,25 /* height of font  */
  ,25 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFONT1_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,17 /* Height of capital characters */
};

