/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (NXP) version 5.38                     *
*        Compiled Nov 24 2016, 16:56:53                              *
*                                                                    *
*        (c) 1998 - 2016 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontSong.c                                            *
* Font:        宋体                                                  *
* Height:      30                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  30                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\新建文本文档 (2).txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5173[120] = { /* code 5173 */
  ________,________,________,________,
  ________,________,________,________,
  ________,_X______,___XX___,________,
  ________,_XX_____,___XXX__,________,
  ________,__XX____,__XX____,________,
  ________,___XX___,__XX____,________,
  ________,___XX___,__X_____,________,
  ________,____X___,_X______,________,
  ________,________,_X______,XX______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______X_,________,_XX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,_____XX_,X_______,________,
  ________,_____XX_,_X______,________,
  ________,____XX__,_X______,________,
  ________,____XX__,__X_____,________,
  ________,___XX___,__XX____,________,
  ________,__XX____,___XX___,________,
  ________,__X_____,____XX__,________,
  ________,XX______,_____XX_,________,
  _______X,X_______,______XX,X_______,
  ______X_,________,_______X,XXXX____,
  ____XX__,________,________,XXX_____,
  __XX____,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5668[120] = { /* code 5668 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  _____XX_,____X___,_X_____X,X_______,
  _____XXX,XXXXXX__,_XXXXXXX,X_______,
  _____XX_,____X___,_X_____X,X_______,
  _____XX_,____X___,_X_____X,X_______,
  _____XX_,____X___,_X_____X,X_______,
  _____XX_,____X___,_X_____X,X_______,
  _____XXX,XXXXX___,_XXXXXXX,X_______,
  _____XX_,____X___,_X_X___X,________,
  ________,_____XXX,____XX__,________,
  ________,____XXX_,_____X__,_X______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,___XX___,_X______,________,
  ________,__XX____,__X_____,________,
  ________,_XX_____,___XX___,________,
  ________,XX______,____XXX_,________,
  ______XX,X_______,______XX,XX______,
  _____XX_,____XX__,XX_____X,XXXX____,
  __XXX_XX,XXXXX___,XXXXXXXX,XXX_____,
  ______X_,____X___,XX_____X,X_______,
  ______X_,____X___,XX_____X,X_______,
  ______X_,____X___,XX_____X,X_______,
  ______X_,____X___,XX_____X,X_______,
  ______XX,XXXXX___,XXXXXXXX,X_______,
  ______X_,____X___,XX_____X,X_______,
  ______X_,________,XX_____X,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5730[120] = { /* code 5730 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,__XX____,________,
  ______XX,________,__XX____,________,
  ______X_,________,__XX____,________,
  ______X_,________,__XX____,________,
  ______X_,_____XX_,__XX____,________,
  ______X_,_____XX_,__XX____,________,
  ______X_,_____XX_,__XX____,X_______,
  ______X_,_____XX_,__XX__XX,XX______,
  ______X_,_____XX_,__XXXX__,X_______,
  ______X_,_XX__XX_,_XXX____,X_______,
  __XXXXXX,X____XXX,X_XX____,X_______,
  ______X_,____XXX_,__XX____,X_______,
  ______X_,_XXX_XX_,__XX____,X_______,
  ______X_,_____XX_,__XX____,X_______,
  ______X_,_____XX_,__XX____,X_______,
  ______X_,_____XX_,__XX____,X_______,
  ______X_,_____XX_,__XX____,X_______,
  ______X_,_____XX_,__XXXXXX,X_______,
  ______X_,_____XX_,__XX___X,X_______,
  ______X_,__XX_XX_,__XX____,__X_____,
  ______XX,XX___XX_,__X_____,__X_____,
  ____XXX_,_____XX_,________,__X_____,
  _XXXX___,_____XX_,________,__XX____,
  __XX____,_____XX_,________,__XXX___,
  ________,_____XXX,XXXXXXXX,XXXX____,
  ________,_______X,XXXXXXXX,XX______,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5757[120] = { /* code 5757 */
  ________,________,________,________,
  ________,________,________,________,
  ______XX,________,XXX_____,________,
  ______XX,________,XX______,________,
  ______XX,________,XX______,________,
  ______XX,________,XX______,________,
  ______XX,________,XX______,________,
  ______XX,________,XX_____X,________,
  ______XX,___XXXXX,XXXXXXXX,XX______,
  ______XX,__X_____,XX_____X,X_______,
  ______XX,_XXX____,XX_____X,X_______,
  __XXXXXX,X_______,XX_____X,X_______,
  ______XX,________,XX_____X,X_______,
  ______XX,________,XX_____X,X_______,
  ______XX,________,XX_____X,X_______,
  ______XX,________,XX_____X,X_X_____,
  ______XX,________,XX_____X,XXXX____,
  ______XX,__XXXXXX,XXXXXXX_,________,
  ______XX,________,X_X_____,________,
  ______XX,_______X,X__X____,________,
  ______XX,_XXX___X,X__X____,________,
  _____XXX,X______X,____X___,________,
  _XXXXX__,______XX,____XX__,________,
  __XX____,_____XX_,_____XX_,________,
  ________,____XX__,______XX,________,
  ________,___XX___,______XX,XX______,
  ________,__XX____,_______X,XXXX____,
  ________,XX______,________,_XX_____,
  ______XX,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5F00[120] = { /* code 5F00 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,__X_____,___XX___,________,
  ________,__X_____,___XX___,________,
  ________,__X_____,___XX___,________,
  ________,__X_____,___XX___,________,
  ________,__X_____,___XX___,________,
  ________,__X_____,___XX___,________,
  ________,__X_____,___XX___,________,
  ________,__X_____,___XX___,_XX_____,
  ________,__X_____,___XX___,XXXX____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,__X_____,___XX___,________,
  ________,__X_____,___XX___,________,
  ________,_XX_____,___XX___,________,
  ________,_XX_____,___XX___,________,
  ________,_XX_____,___XX___,________,
  ________,_X______,___XX___,________,
  ________,XX______,___XX___,________,
  ________,X_______,___XX___,________,
  _______X,X_______,___XX___,________,
  ______XX,________,___XX___,________,
  _____XX_,________,___XX___,________,
  ____XX__,________,___XX___,________,
  ___X____,________,___XX___,________,
  __X_____,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6253[120] = { /* code 6253 */
  ________,________,________,________,
  ________,________,________,________,
  _______X,X_______,________,________,
  _______X,X_______,________,________,
  _______X,X_______,________,__X_____,
  _______X,X_______,________,_XXX____,
  _______X,X_____XX,XXXXXXXX,X_______,
  _______X,X___X___,____XX__,________,
  __XXXXXX,XXXXXX__,____XX__,________,
  _______X,X_______,____XX__,________,
  _______X,X_______,____XX__,________,
  _______X,X_______,____XX__,________,
  _______X,X_______,____XX__,________,
  _______X,X__XX___,____XX__,________,
  _______X,XXX_____,____XX__,________,
  ______XX,X_______,____XX__,________,
  ___XXXXX,X_______,____XX__,________,
  __XXX__X,X_______,____XX__,________,
  ___X___X,X_______,____XX__,________,
  _______X,X_______,____XX__,________,
  _______X,X_______,____XX__,________,
  _______X,X_______,____XX__,________,
  _______X,X_______,____XX__,________,
  _______X,X_______,____XX__,________,
  _______X,X_______,____XX__,________,
  _______X,X_______,____XX__,________,
  ___XXXXX,X_______,_XXXXX__,________,
  ______XX,X_______,__XXX___,________,
  ______X_,________,___X____,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6267[120] = { /* code 6267 */
  ________,________,________,________,
  ________,________,________,________,
  _______X,X_______,XX______,________,
  _______X,X_______,XX______,________,
  _______X,X_______,XX______,________,
  _______X,X_______,XX______,________,
  _______X,X_______,XX______,________,
  _______X,X__X____,XX______,________,
  _______X,X_XXX___,XX____X_,________,
  __XXXXXX,XX______,XXXXXXXX,________,
  _______X,X___XXXX,XX____X_,________,
  _______X,X_______,XX____X_,________,
  _______X,X_______,XX____X_,________,
  _______X,X__XX___,XX____X_,________,
  _______X,XXX_____,XX____X_,________,
  ______XX,X_______,X_____X_,________,
  ___XXXXX,X___XXX_,X_____X_,________,
  _XXXX__X,X______X,X_____X_,________,
  __X____X,X______X,XXX___X_,________,
  _______X,X______X,__XX__X_,________,
  _______X,X_____XX,___XX_X_,________,
  _______X,X_____XX,___XX_XX,___X____,
  _______X,X____XX_,______XX,___X____,
  _______X,X____X__,_______X,___X____,
  _______X,X___XX__,_______X,X__X____,
  _______X,X___X___,________,XXXX____,
  ___XXXXX,___X____,________,_XXX____,
  _____XXX,__X_____,________,__XX____,
  ______X_,XX______,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6A21[120] = { /* code 6A21 */
  ________,________,________,________,
  ________,_______X,________,________,
  ______XX,X______X,XX___XX_,________,
  ______XX,_______X,X____XX_,________,
  ______XX,_______X,X____XX_,__X_____,
  ______XX,___XXXXX,XXXXXXXX,XXXX____,
  ______XX,_______X,X____XX_,________,
  ______XX,__X____X,X____XX_,________,
  _XXXXXXX,XXXX___X,X____X__,________,
  ______XX,_____XX_,________,X_______,
  ______XX,_____XXX,XXXXXXXX,X_______,
  _____XXX,_____XX_,________,X_______,
  _____XXX,X____XX_,________,X_______,
  _____XXX,XX___XXX,XXXXXXXX,X_______,
  ____XXXX,_XX__XX_,________,X_______,
  ____X_XX,__XX_XX_,________,X_______,
  ____X_XX,__X__XX_,________,X_______,
  ___X__XX,_____XXX,XXXXXXXX,X_______,
  ___X__XX,_____X__,__X_____,________,
  __X___XX,________,__X_____,__X_____,
  _X____XX,________,__X_____,_XXX____,
  ______XX,__XXXXXX,XXXXXXXX,X_______,
  ______XX,________,_XX_X___,________,
  ______XX,________,XX___X__,________,
  ______XX,________,XX___XX_,________,
  ______XX,_______X,X_____XX,________,
  ______XX,______XX,_______X,XXXX____,
  ______XX,____XX__,________,XXX_____,
  ______X_,_XXX____,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6D4B[120] = { /* code 6D4B */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,_X______,
  ____XX__,_XX_____,_XX_____,_XX_____,
  _____XX_,_XXXXXXX,XXX_____,_XX_____,
  _____XX_,_XX_____,_X______,_XX_____,
  ______X_,_XX_____,_X___X__,_XX_____,
  ________,_XX_____,_X___XX_,_XX_____,
  ________,_XX__XX_,_X___XX_,_XX_____,
  __XX____,_XX__XX_,_X___XX_,_XX_____,
  ___XX__X,XXX__XX_,_X___XX_,_XX_____,
  ___XX__X,_XX__XX_,_X___XX_,_XX_____,
  ___XX__X,_XX__XX_,_X___XX_,_XX_____,
  _______X,_XX__XX_,_X___XX_,_XX_____,
  ______X_,_XX__XX_,_X___XX_,_XX_____,
  ______X_,_XX__XX_,_X___XX_,_XX_____,
  ______X_,_XX__X__,_X___XX_,_XX_____,
  ______X_,_XX__X__,_X___XX_,_XX_____,
  _____XX_,_XX__X__,_X___XX_,_XX_____,
  _____X__,_XX__X__,_X___XX_,_XX_____,
  __XXXX__,_XX_XX__,_____XX_,_XX_____,
  ____XX__,____XX__,_____XX_,_XX_____,
  ____XX__,____X_XX,________,_XX_____,
  ____XX__,___XX___,X_______,_XX_____,
  ____XX__,__XX____,XX______,_XX_____,
  ____XX__,__X_____,_XX_____,_XX_____,
  ____XX__,_X______,_XX___XX,XXX_____,
  _______X,X_______,_______X,XX______,
  ______X_,________,________,X_______,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_754C[120] = { /* code 754C */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  _______X,XXXXXXXX,XXXXXXXX,________,
  _______X,______XX,______XX,________,
  _______X,______XX,______XX,________,
  _______X,______XX,______XX,________,
  _______X,XXXXXXXX,XXXXXXXX,________,
  _______X,______XX,______XX,________,
  _______X,______XX,______XX,________,
  _______X,______XX,______XX,________,
  _______X,______XX,______XX,________,
  _______X,XXXXXXX_,XXXXXXXX,________,
  ________,____XX__,__X_____,________,
  ________,___XX___,__XX____,________,
  ________,__XX____,___XX___,________,
  ________,_XX_____,____XXX_,________,
  ________,XX_XXX__,___X__XX,XX______,
  _______X,X__XX___,___X___X,XXXX____,
  _____XX_,___XX___,___X____,__X_____,
  __XXX___,___X____,___X____,________,
  ________,__XX____,___X____,________,
  ________,__XX____,___X____,________,
  ________,__X_____,___X____,________,
  ________,_XX_____,___X____,________,
  ________,XX______,___X____,________,
  _______X,X_______,___X____,________,
  _____XX_,________,___X____,________,
  ___XX___,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_884C[120] = { /* code 884C */
  ________,________,________,________,
  ________,________,________,________,
  ________,XX______,________,________,
  ________,XX______,________,X_______,
  _______X,X_______,_______X,XX______,
  ______XX,______XX,XXXXXXX_,________,
  ______X_,________,________,________,
  _____X__,________,________,________,
  ____X___,_XX_____,________,________,
  ___X____,_XX_____,________,________,
  ________,XX______,________,__X_____,
  ________,XX______,________,_XXX____,
  _______X,X___XXXX,XXXXXXXX,X_______,
  ______XX,________,____X___,________,
  ______XX,X_______,____X___,________,
  _____X_X,X_______,____X___,________,
  ____X__X,X_______,____X___,________,
  ___X___X,X_______,____X___,________,
  __X____X,X_______,____X___,________,
  _______X,X_______,____X___,________,
  _______X,X_______,____X___,________,
  _______X,X_______,____X___,________,
  _______X,X_______,____X___,________,
  _______X,X_______,____X___,________,
  _______X,X_______,____X___,________,
  _______X,X_______,___XX___,________,
  _______X,X______X,XXXXX___,________,
  _______X,X_______,__XXX___,________,
  _______X,________,__X_____,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_8BD5[120] = { /* code 8BD5 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,___XX___,________,
  ____X___,________,___XXX_X,X_______,
  ____XX__,________,___XX___,XX______,
  _____XX_,________,___XX___,_XX_____,
  _____XXX,________,___XX___,_X______,
  ______XX,________,____X___,__X_____,
  ______X_,________,____X___,_XXX____,
  ________,__XXXXXX,XXXXXXXX,X_______,
  ________,________,____X___,________,
  ________,________,____X___,________,
  ______X_,________,____XX__,________,
  __XXXXXX,________,__X_XX__,________,
  ______XX,__XXXXXX,XXX_XX__,________,
  ______XX,______XX,___XXX__,________,
  ______XX,______XX,_____X__,________,
  ______XX,______XX,_____X__,________,
  ______XX,______XX,_____XX_,________,
  ______XX,______XX,_____XX_,________,
  ______XX,___X__XX,______X_,________,
  ______XX,__X___XX,______XX,________,
  ______XX,_XX___XX,__XX__XX,___X____,
  ______XX,XX____XX,XX_____X,X__X____,
  ______XX,X__XXXX_,________,XX_X____,
  ______XX,X__XX___,________,XXXX____,
  ______XX,___X____,________,_XXX____,
  ________,________,________,__XX____,
  ________,________,________,____X___,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_901A[120] = { /* code 901A */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,_______X,________,
  ____X___,___XXXXX,XXXXXXXX,X_______,
  ____XX__,________,______XX,________,
  _____XX_,_______X,X___XX__,________,
  _____XX_,________,_XXX____,________,
  ______X_,________,_XXX____,________,
  ________,___XX___,__X_____,XXX_____,
  ________,___X_XXX,XXXXXXXX,XX______,
  ________,___X____,_XX_____,XX______,
  ______X_,___X____,_XX_____,XX______,
  __XXXXXX,___X____,_XX_____,XX______,
  ______X_,___XXXXX,XXXXXXXX,XX______,
  ______X_,___X____,_XX_____,XX______,
  ______X_,___X____,_XX_____,XX______,
  ______X_,___X____,_XX_____,XX______,
  ______X_,___XXXXX,XXXXXXXX,XX______,
  ______X_,___X____,_XX_____,XX______,
  ______X_,___X____,_XX_____,XX______,
  ______X_,___X____,_XX_____,XX______,
  ______X_,___X____,_XX_____,XX______,
  ______XX,___X____,_XX__XXX,XX______,
  ____XX_X,X__X____,_X_____X,XX______,
  __XXX___,_X______,________,________,
  _XXX____,__XXXX__,________,___XX___,
  __X_____,____XXXX,XXXXXXXX,XXX_____,
  ________,________,XXXXXXXX,XXX_____,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_9053[120] = { /* code 9053 */
  ________,________,________,________,
  ________,________,________,________,
  ____X___,_____X__,______XX,________,
  _____XX_,______XX,_____XXX,________,
  _____XX_,______XX,_____X__,________,
  ______XX,_______X,X___XX__,________,
  ______XX,_______X,____X___,_XX_____,
  ________,__XXXXXX,XXXXXXXX,XXXX____,
  ________,________,_XX_____,________,
  ________,________,_X______,________,
  ________,_____X__,_X_____X,X_______,
  _XXXXXXX,_____XXX,X_XXXXXX,X_______,
  ______XX,_____X__,_______X,X_______,
  ______X_,_____X__,_______X,X_______,
  ______X_,_____XXX,XXXXXXXX,X_______,
  ______X_,_____X__,_______X,X_______,
  ______X_,_____X__,_______X,X_______,
  ______X_,_____X__,_______X,X_______,
  ______X_,_____XXX,XXXXXXXX,X_______,
  ______X_,_____X__,_______X,X_______,
  ______X_,_____X__,_______X,X_______,
  ______X_,_____X__,_______X,X_______,
  _____XXX,_____XXX,XXXXXXXX,X_______,
  ___XX___,X____X__,_______X,________,
  __XX____,_X______,________,________,
  __X_____,__XXX___,________,________,
  ________,____XXXX,XXXXXXXX,XXXX____,
  ________,________,XXXXXXXX,XXX_____,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_94C1[120] = { /* code 94C1 */
  ________,________,________,________,
  ________,________,________,________,
  ______XX,________,___XX___,________,
  _____XXX,________,___XX___,________,
  _____XX_,_______X,___XX___,________,
  _____XX_,______XX,X__XX___,________,
  _____X__,__XX__XX,___XX___,________,
  ____XXXX,XX____XX,___XX___,_X______,
  ____X___,______X_,___XX___,XXX_____,
  ___XX___,______XX,XXXXXXXX,________,
  ___X____,__X__XX_,___X____,________,
  ___XXXXX,XXXX_X__,___X____,________,
  __X___XX,_____X__,___X____,________,
  _X____XX,____X___,___X____,________,
  ______XX,________,___X____,__X_____,
  ______XX,________,___X____,_XXX____,
  ______XX,__XXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XX______,__XXX___,________,
  ______XX,________,__X__X__,________,
  ______XX,________,_XX__X__,________,
  ______XX,________,_XX__XX_,________,
  ______XX,____X___,XX____X_,________,
  ______XX,__XX____,X_____XX,________,
  ______XX,XX_____X,X______X,________,
  ______XX,X_____XX,_______X,X_______,
  _____XXX,_____XX_,________,XX______,
  ______X_,____XX__,________,XXXX____,
  ________,___X____,________,_XX_____,
  ________,_XX_____,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_95ED[120] = { /* code 95ED */
  ________,________,________,________,
  ________,________,________,________,
  _______X,________,________,________,
  ________,XX______,________,_X______,
  ________,XX___XXX,XXXXXXXX,XXX_____,
  ____X___,_X______,________,_XX_____,
  ____XXX_,_X______,X_______,_X______,
  ____XX__,________,XXX_____,_X______,
  ____XX__,________,XX______,_X______,
  ____XX__,________,XX______,_X______,
  ____XX__,________,XX______,_X______,
  ____XX_X,XXXXXXXX,XXXXXXX_,_X______,
  ____XX__,_______X,XX______,_X______,
  ____XX__,______XX,XX______,_X______,
  ____XX__,______X_,XX______,_X______,
  ____XX__,_____XX_,XX______,_X______,
  ____XX__,____XX__,XX______,_X______,
  ____XX__,____X___,XX______,_X______,
  ____XX__,___X____,XX______,_X______,
  ____XX__,__X_____,XX______,_X______,
  ____XX__,_X______,XX______,_X______,
  ____XX__,X_______,XX______,_X______,
  ____XX_X,________,XX______,_X______,
  ____XX__,_____XXX,XX______,_X______,
  ____XX__,_______X,XX______,_X______,
  ____XX__,_______X,________,_X______,
  ____XX__,________,_____XXX,XX______,
  ____XX__,________,_______X,XX______,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_9762[120] = { /* code 9762 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,__X_____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  __X_____,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,____XX__,________,________,
  ________,____X___,________,________,
  ________,____X___,________,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___XXXXX,XXX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___XXXXX,XXX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XX__,___X____,_XX_____,XX______,
  ____XXXX,XXX_XXXX,X__XXXXX,XX______,
  ____XX__,________,________,XX______,
  ____X___,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFontSong_CharInfo[17] = {
   {  30,  30,  4, acGUI_FontFontSong_5173 } /* code 5173 */
  ,{  30,  30,  4, acGUI_FontFontSong_5668 } /* code 5668 */
  ,{  30,  30,  4, acGUI_FontFontSong_5730 } /* code 5730 */
  ,{  30,  30,  4, acGUI_FontFontSong_5757 } /* code 5757 */
  ,{  30,  30,  4, acGUI_FontFontSong_5F00 } /* code 5F00 */
  ,{  30,  30,  4, acGUI_FontFontSong_6253 } /* code 6253 */
  ,{  30,  30,  4, acGUI_FontFontSong_6267 } /* code 6267 */
  ,{  30,  30,  4, acGUI_FontFontSong_6A21 } /* code 6A21 */
  ,{  30,  30,  4, acGUI_FontFontSong_6D4B } /* code 6D4B */
  ,{  30,  30,  4, acGUI_FontFontSong_754C } /* code 754C */
  ,{  30,  30,  4, acGUI_FontFontSong_884C } /* code 884C */
  ,{  30,  30,  4, acGUI_FontFontSong_8BD5 } /* code 8BD5 */
  ,{  30,  30,  4, acGUI_FontFontSong_901A } /* code 901A */
  ,{  30,  30,  4, acGUI_FontFontSong_9053 } /* code 9053 */
  ,{  30,  30,  4, acGUI_FontFontSong_94C1 } /* code 94C1 */
  ,{  30,  30,  4, acGUI_FontFontSong_95ED } /* code 95ED */
  ,{  30,  30,  4, acGUI_FontFontSong_9762 } /* code 9762 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop17 = {
   0x9762 /* first character */
  ,0x9762 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 16] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop16 = {
   0x95ED /* first character */
  ,0x95ED /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 15] /* address of first character */
  ,&GUI_FontFontSong_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop15 = {
   0x94C1 /* first character */
  ,0x94C1 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFontSong_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop14 = {
   0x9053 /* first character */
  ,0x9053 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 13] /* address of first character */
  ,&GUI_FontFontSong_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop13 = {
   0x901A /* first character */
  ,0x901A /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFontSong_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop12 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFontSong_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop11 = {
   0x884C /* first character */
  ,0x884C /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 10] /* address of first character */
  ,&GUI_FontFontSong_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop10 = {
   0x754C /* first character */
  ,0x754C /* last character  */
  ,&GUI_FontFontSong_CharInfo[  9] /* address of first character */
  ,&GUI_FontFontSong_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop9 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontFontSong_CharInfo[  8] /* address of first character */
  ,&GUI_FontFontSong_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop8 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  7] /* address of first character */
  ,&GUI_FontFontSong_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop7 = {
   0x6267 /* first character */
  ,0x6267 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  6] /* address of first character */
  ,&GUI_FontFontSong_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop6 = {
   0x6253 /* first character */
  ,0x6253 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  5] /* address of first character */
  ,&GUI_FontFontSong_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop5 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  4] /* address of first character */
  ,&GUI_FontFontSong_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop4 = {
   0x5757 /* first character */
  ,0x5757 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  3] /* address of first character */
  ,&GUI_FontFontSong_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop3 = {
   0x5730 /* first character */
  ,0x5730 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  2] /* address of first character */
  ,&GUI_FontFontSong_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop2 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  1] /* address of first character */
  ,&GUI_FontFontSong_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop1 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontSong_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,30 /* height of font  */
  ,30 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontSong_Prop1}
  ,26 /* Baseline */
  ,13 /* Height of lowercase characters */
  ,21 /* Height of capital characters */
};

